### ISSUE TITLE
Errno 2

### ISSUE THREAD

**Issue by merolaika** [iamsoroush/cryptosignal#2]
HEllo, when i use this command, its give me error python3 run main.py

python3: can't open file 'run': [Errno 2] No such file or directory

and when i use python3 main.py i get this

`python3 main.py 
/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography import x509
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from binance.websockets import BinanceSocketManager
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/binance/websockets.py", line 4, in <module>
    from autobahn.twisted.websocket import WebSocketClientFactory, \
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/autobahn/twisted/__init__.py", line 36, in <module>
    from autobahn.twisted.util import sleep
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/autobahn/twisted/util.py", line 94, in <module>
    from twisted.protocols.tls import TLSMemoryBIOProtocol
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/home/mero/anaconda3/envs/crypto/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'` 

 i solved this from this line

pip install pip --upgrade
pip install pyopenssl --upgrade

**Comment by iamsoroush** [comment]
that's a typo, just remove ``run``
